// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbnozWnMa3nVtRUDPwYg3x_NAy1D323bw',
    appId: '1:749318451543:web:539e8efcc85e32e2d04e12',
    messagingSenderId: '749318451543',
    projectId: 'annual-leave-backend',
    authDomain: 'annual-leave-backend.firebaseapp.com',
    storageBucket: 'annual-leave-backend.firebasestorage.app',
    measurementId: 'G-ZZ5C7Q1XBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvb7w11uZGaEYjh7G4KihC5FG-iu1meA',
    appId: '1:749318451543:android:120ac47f25c8977bd04e12',
    messagingSenderId: '749318451543',
    projectId: 'annual-leave-backend',
    storageBucket: 'annual-leave-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFWc8S-pqIUtKDoNfL-DRvwUIdImjx5aw',
    appId: '1:749318451543:ios:faf19c15aea34a2ed04e12',
    messagingSenderId: '749318451543',
    projectId: 'annual-leave-backend',
    storageBucket: 'annual-leave-backend.firebasestorage.app',
    iosBundleId: 'com.dyinfotech.annualLeave',
  );
}
